/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a.donde.comemos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author jordi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private static String USER_NAME = "adondecomemosentegus@gmail.com";  // GMail user name (just the part before "@gmail.com")
    private static String PASSWORD = "Hacktegus2015"; // GMail password
    private String RECIPIENT;

    public Principal() {
        initComponents();
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
        //Dba db = new Dba("./Base de Datos de Restaurantes.accdb");
        //db.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jP_comida = new javax.swing.JPanel();
        jL_ubicacion_coordenadas = new javax.swing.JLabel();
        jB_comida_retorno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCB_comida_filtros = new javax.swing.JComboBox();
        jP_comida_esconder = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jCB_comida_especifico = new javax.swing.JComboBox();
        jB_comida_aceptar = new javax.swing.JButton();
        jP_dinero = new javax.swing.JPanel();
        jB_dinero_retorno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jB_dinero_aceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jS_dinero_maximo = new javax.swing.JSlider();
        jTF_dinero_valor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jP_resultados = new javax.swing.JPanel();
        jB_resultados_retorno = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jP_principal = new javax.swing.JPanel();
        jL_nombreApp = new javax.swing.JLabel();
        jB_principal_filtroComida = new javax.swing.JButton();
        jB_principal_filtroDinero = new javax.swing.JButton();
        jB_principal_filtroUbicacion = new javax.swing.JButton();
        jB_principal_filtroSugerencias = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jL_principal_buscarComida = new javax.swing.JLabel();
        jL_principal_buscarPrecio = new javax.swing.JLabel();
        jL_principal_buscarDistancia = new javax.swing.JLabel();
        jB_principal_Buscar = new javax.swing.JButton();
        jP_ubicacion = new javax.swing.JPanel();
        jB_ubicacion_retorno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jP_sugerencias = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_sugerencias_texto = new javax.swing.JTextArea();
        jB_sugerencias_enviar = new javax.swing.JButton();
        jB_sugerencias_retorno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_sugerencias_correo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));
        setResizable(false);

        jP_comida.setBackground(new java.awt.Color(255, 153, 51));
        jP_comida.setForeground(new java.awt.Color(255, 153, 51));
        jP_comida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jP_comida.add(jL_ubicacion_coordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 392, -1, -1));

        jB_comida_retorno.setText("back");
        jB_comida_retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_comida_retornoMouseClicked(evt);
            }
        });
        jP_comida.add(jB_comida_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        jLabel10.setText("COMIDA");
        jP_comida.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel14.setText("Filtros");
        jP_comida.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jCB_comida_filtros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar por Restaurante", "Buscar por Comida", "Buscar por Sabor", "Buscar por Tipo", "No se que comer" }));
        jCB_comida_filtros.setSelectedIndex(4);
        jCB_comida_filtros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_comida_filtrosItemStateChanged(evt);
            }
        });
        jP_comida.add(jCB_comida_filtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, -1));

        jP_comida_esconder.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jP_comida_esconderLayout = new javax.swing.GroupLayout(jP_comida_esconder);
        jP_comida_esconder.setLayout(jP_comida_esconderLayout);
        jP_comida_esconderLayout.setHorizontalGroup(
            jP_comida_esconderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jP_comida_esconderLayout.setVerticalGroup(
            jP_comida_esconderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jP_comida.add(jP_comida_esconder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, -1));

        jLabel15.setText("Especifique");
        jP_comida.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        jCB_comida_especifico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jP_comida.add(jCB_comida_especifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 30));

        jB_comida_aceptar.setText("ok");
        jB_comida_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_comida_aceptarMouseClicked(evt);
            }
        });
        jP_comida.add(jB_comida_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 90, 90));

        jP_dinero.setBackground(new java.awt.Color(255, 204, 0));
        jP_dinero.setForeground(new java.awt.Color(255, 204, 0));
        jP_dinero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_dinero_retorno.setText("back");
        jB_dinero_retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_dinero_retornoMouseClicked(evt);
            }
        });
        jP_dinero.add(jB_dinero_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 63, 61));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel6.setText("DINERO");
        jP_dinero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jB_dinero_aceptar.setText("ok");
        jB_dinero_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_dinero_aceptarMouseClicked(evt);
            }
        });
        jB_dinero_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_dinero_aceptarActionPerformed(evt);
            }
        });
        jP_dinero.add(jB_dinero_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 91));

        jLabel7.setText("Maximo que desea gastar:");
        jP_dinero.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 128, -1, -1));

        jS_dinero_maximo.setMajorTickSpacing(100);
        jS_dinero_maximo.setMaximum(1000);
        jS_dinero_maximo.setMinimum(100);
        jS_dinero_maximo.setMinorTickSpacing(50);
        jS_dinero_maximo.setOrientation(javax.swing.JSlider.VERTICAL);
        jS_dinero_maximo.setPaintLabels(true);
        jS_dinero_maximo.setPaintTicks(true);
        jS_dinero_maximo.setSnapToTicks(true);
        jS_dinero_maximo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_dinero_maximoStateChanged(evt);
            }
        });
        jP_dinero.add(jS_dinero_maximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 108, 223));

        jTF_dinero_valor.setText("100");
        jP_dinero.add(jTF_dinero_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 30));

        jLabel8.setText("Lps.");
        jP_dinero.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        jP_resultados.setBackground(new java.awt.Color(0, 153, 153));
        jP_resultados.setForeground(new java.awt.Color(0, 153, 153));
        jP_resultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_resultados_retorno.setText("back");
        jB_resultados_retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_resultados_retornoMouseClicked(evt);
            }
        });
        jP_resultados.add(jB_resultados_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 57, 58));

        jLabel13.setText("RESULTADOS");
        jP_resultados.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"furiwa", "arroz",  new Integer(100),  new Double(2.0)},
                {"los toneles", "pastelitos",  new Integer(50),  new Double(1.5)},
                {null, null, null, null}
            },
            new String [] {
                "Restaurante", "Comida", "Precio", "Distancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jP_resultados.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 380, 283));

        jP_principal.setBackground(new java.awt.Color(0, 153, 0));
        jP_principal.setForeground(new java.awt.Color(0, 102, 0));
        jP_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_nombreApp.setFont(new java.awt.Font("Hollywood Capital", 1, 36)); // NOI18N
        jL_nombreApp.setForeground(new java.awt.Color(255, 153, 0));
        jL_nombreApp.setText("¿A DONDE COMEMOS?");
        jP_principal.add(jL_nombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jB_principal_filtroComida.setBackground(new java.awt.Color(255, 255, 153));
        jB_principal_filtroComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/donde/comemos/restaurant35.png"))); // NOI18N
        jB_principal_filtroComida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_principal_filtroComida.setContentAreaFilled(false);
        jB_principal_filtroComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_principal_filtroComidaMouseClicked(evt);
            }
        });
        jP_principal.add(jB_principal_filtroComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 145, 135));

        jB_principal_filtroDinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/donde/comemos/money1321.png"))); // NOI18N
        jB_principal_filtroDinero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_principal_filtroDinero.setContentAreaFilled(false);
        jB_principal_filtroDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_principal_filtroDineroMouseClicked(evt);
            }
        });
        jP_principal.add(jB_principal_filtroDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 85, 144, 135));

        jB_principal_filtroUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/donde/comemos/search87.png"))); // NOI18N
        jB_principal_filtroUbicacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_principal_filtroUbicacion.setContentAreaFilled(false);
        jB_principal_filtroUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_principal_filtroUbicacionMouseClicked(evt);
            }
        });
        jP_principal.add(jB_principal_filtroUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 226, 145, 137));

        jB_principal_filtroSugerencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/donde/comemos/mail87.png"))); // NOI18N
        jB_principal_filtroSugerencias.setToolTipText("");
        jB_principal_filtroSugerencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_principal_filtroSugerencias.setContentAreaFilled(false);
        jB_principal_filtroSugerencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_principal_filtroSugerenciasMouseClicked(evt);
            }
        });
        jP_principal.add(jB_principal_filtroSugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 226, 144, 137));

        jLabel2.setFont(new java.awt.Font("Hollywood Capital", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("FILTROS");
        jP_principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jL_principal_buscarComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_principal_buscarComida.setText("BUSCAR: Cualquier Comida");
        jP_principal.add(jL_principal_buscarComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 270, 20));

        jL_principal_buscarPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_principal_buscarPrecio.setText("POR: Lps 100");
        jP_principal.add(jL_principal_buscarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 270, -1));

        jL_principal_buscarDistancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_principal_buscarDistancia.setText("A: 1 km");
        jP_principal.add(jL_principal_buscarDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 440, 260, -1));

        jB_principal_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_principal_BuscarMouseClicked(evt);
            }
        });
        jP_principal.add(jB_principal_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 369, 295, 103));

        jP_ubicacion.setBackground(new java.awt.Color(0, 0, 204));
        jP_ubicacion.setForeground(new java.awt.Color(0, 0, 204));
        jP_ubicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_ubicacion_retorno.setText("back");
        jB_ubicacion_retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_ubicacion_retornoMouseClicked(evt);
            }
        });
        jP_ubicacion.add(jB_ubicacion_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 56, 52));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UBICACION");
        jP_ubicacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 70, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RADIO MAXIMO (m):");
        jP_ubicacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, -1, -1));

        jSlider1.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(200);
        jSlider1.setMaximum(2000);
        jSlider1.setMinimum(200);
        jSlider1.setMinorTickSpacing(100);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jP_ubicacion.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 292, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/donde/comemos/staticmap.png"))); // NOI18N
        jP_ubicacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 276, 221));

        jButton1.setText("Establecer Rango");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jP_ubicacion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 434, 286, -1));

        jP_sugerencias.setBackground(new java.awt.Color(204, 0, 0));
        jP_sugerencias.setForeground(new java.awt.Color(204, 0, 0));
        jP_sugerencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Hollywood Capital", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUGERENCIAS");
        jP_sugerencias.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 301, -1));

        jTA_sugerencias_texto.setColumns(20);
        jTA_sugerencias_texto.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        jTA_sugerencias_texto.setForeground(new java.awt.Color(153, 153, 153));
        jTA_sugerencias_texto.setLineWrap(true);
        jTA_sugerencias_texto.setRows(5);
        jTA_sugerencias_texto.setText("Sugerencia");
        jTA_sugerencias_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTA_sugerencias_textoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTA_sugerencias_texto);

        jP_sugerencias.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 282, 134));

        jB_sugerencias_enviar.setText("Enviar");
        jB_sugerencias_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_sugerencias_enviarMouseClicked(evt);
            }
        });
        jP_sugerencias.add(jB_sugerencias_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 387, 92, 93));

        jB_sugerencias_retorno.setText("Back");
        jB_sugerencias_retorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_sugerencias_retornoMouseClicked(evt);
            }
        });
        jP_sugerencias.add(jB_sugerencias_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 57, 55));

        jLabel3.setFont(new java.awt.Font("Courier", 0, 14)); // NOI18N
        jLabel3.setText("Si encontro un error o falta ");
        jP_sugerencias.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier", 0, 14)); // NOI18N
        jLabel4.setText("informacion, indiquelo abajo");
        jP_sugerencias.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        jLabel5.setText("Su correo:");
        jP_sugerencias.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 183, -1, -1));

        jTF_sugerencias_correo.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        jTF_sugerencias_correo.setForeground(new java.awt.Color(153, 153, 153));
        jTF_sugerencias_correo.setText("alguien@correo.com");
        jTF_sugerencias_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTF_sugerencias_correoMouseClicked(evt);
            }
        });
        jP_sugerencias.add(jTF_sugerencias_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 282, -1));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_comida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_ubicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_dinero, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_sugerencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 301, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_comida, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_ubicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_dinero, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_sugerencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_resultados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jP_comida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jP_dinero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jP_resultados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jP_principal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jP_ubicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jP_sugerencias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_principal_filtroComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_principal_filtroComidaMouseClicked
        jP_principal.setVisible(false);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(true);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
        jCB_comida_filtros.setSelectedIndex(4);
        jP_comida_esconder.setVisible(true);
        jCB_comida_especifico.setEnabled(false);
    }//GEN-LAST:event_jB_principal_filtroComidaMouseClicked

    private void jB_principal_filtroSugerenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_principal_filtroSugerenciasMouseClicked
        jP_principal.setVisible(false);
        jP_sugerencias.setVisible(true);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
        jTF_sugerencias_correo.setForeground(new Color(153, 153, 153));
        jTA_sugerencias_texto.setForeground(new Color(153, 153, 153));
        jTA_sugerencias_texto.setText("Sugerencia");
        jTF_sugerencias_correo.setText("alguien@correo.com");
    }//GEN-LAST:event_jB_principal_filtroSugerenciasMouseClicked

    private void jB_principal_filtroDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_principal_filtroDineroMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(false);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(true);
        jP_resultados.setVisible(false);
        jS_dinero_maximo.setValue(100);
        jTF_dinero_valor.setText("100");
    }//GEN-LAST:event_jB_principal_filtroDineroMouseClicked

    private void jB_principal_filtroUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_principal_filtroUbicacionMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(false);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(true);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);

    }//GEN-LAST:event_jB_principal_filtroUbicacionMouseClicked

    private void jB_principal_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_principal_BuscarMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(false);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(true);
    }//GEN-LAST:event_jB_principal_BuscarMouseClicked

    private void jB_sugerencias_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_sugerencias_enviarMouseClicked
        // TODO add your handling code here:
        email e = new email();
        boolean validacion = false;
        if (!jTA_sugerencias_texto.getText().equals("Sugerencia") && !jTF_sugerencias_correo.getText().equals("alguien@correo.com") && !jTA_sugerencias_texto.getText().equals("Gracias por su aporte, su sugerencia ha sido registrada")) {
            if (!jTF_sugerencias_correo.getText().isEmpty() && !jTA_sugerencias_texto.getText().isEmpty()) {
                validacion = true;
            }
        }
        if (validacion) {
            jTA_sugerencias_texto.setText("Gracias por su aporte, su sugerencia ha sido registrada");
            RECIPIENT = jTF_sugerencias_correo.getText();
            String from = USER_NAME;
            String[] us = {from};
            String pass = PASSWORD;
            String[] to = {RECIPIENT}; // list of recipient email addresses
            String subject = "Sugerencias a donde comemos";
            String body = jTA_sugerencias_texto.getText() + "\n" + RECIPIENT;
            e.sendFromGMail(from, pass, us, subject, body);
            e.sendFromGMail(from, pass, to, subject, "Su sugerencia fue recibida");
        }

    }//GEN-LAST:event_jB_sugerencias_enviarMouseClicked

    private void jB_sugerencias_retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_sugerencias_retornoMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_sugerencias_retornoMouseClicked

    private void jTF_sugerencias_correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF_sugerencias_correoMouseClicked
        // TODO add your handling code here:
        jTF_sugerencias_correo.setText("");
        jTF_sugerencias_correo.setForeground(Color.black);
    }//GEN-LAST:event_jTF_sugerencias_correoMouseClicked

    private void jTA_sugerencias_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTA_sugerencias_textoMouseClicked
        // TODO add your handling code here:
        jTA_sugerencias_texto.setText("");
        jTA_sugerencias_texto.setForeground(Color.black);
    }//GEN-LAST:event_jTA_sugerencias_textoMouseClicked

    private void jB_resultados_retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_resultados_retornoMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_resultados_retornoMouseClicked

    private void jB_ubicacion_retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ubicacion_retornoMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_ubicacion_retornoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        rango = jSlider1.getValue();
        System.out.println(rango);
        jL_principal_buscarDistancia.setText("A: " + rango / 1000 + " km");
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jS_dinero_maximoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_dinero_maximoStateChanged
        // TODO add your handling code here:
        jTF_dinero_valor.setText(Integer.toString(jS_dinero_maximo.getValue()));
    }//GEN-LAST:event_jS_dinero_maximoStateChanged

    private void jB_dinero_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_dinero_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_dinero_aceptarActionPerformed

    private void jB_dinero_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_dinero_aceptarMouseClicked
        // TODO add your handling code here:
        jL_principal_buscarPrecio.setText("POR: Lps " + jTF_dinero_valor.getText());
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_dinero_aceptarMouseClicked

    private void jB_dinero_retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_dinero_retornoMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_dinero_retornoMouseClicked

    private void jB_comida_retornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_comida_retornoMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_comida_retornoMouseClicked

    private void jB_comida_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_comida_aceptarMouseClicked
        // TODO add your handling code here:
        jP_principal.setVisible(true);
        jP_sugerencias.setVisible(false);
        jP_ubicacion.setVisible(false);
        jP_comida.setVisible(false);
        jP_dinero.setVisible(false);
        jP_resultados.setVisible(false);
    }//GEN-LAST:event_jB_comida_aceptarMouseClicked

    private void jCB_comida_filtrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_comida_filtrosItemStateChanged
        // TODO add your handling code here:
        if (jCB_comida_filtros.getSelectedIndex() != 4) {
            if (jCB_comida_filtros.getSelectedIndex() == 0) {
                jP_comida_esconder.setVisible(false);
                jCB_comida_especifico.setEnabled(true);
                
            } else if (jCB_comida_filtros.getSelectedIndex() == 1) {
                jP_comida_esconder.setVisible(false);
                jCB_comida_especifico.setEnabled(true);
            } else if (jCB_comida_filtros.getSelectedIndex() == 2) {
                jP_comida_esconder.setVisible(false);
                jCB_comida_especifico.setEnabled(true);
            } else if (jCB_comida_filtros.getSelectedIndex() == 3) {
                jP_comida_esconder.setVisible(false);
                jCB_comida_especifico.setEnabled(true);
            }
        } else {
            jP_comida_esconder.setVisible(true);
            jCB_comida_especifico.setEnabled(false);
        }
    }//GEN-LAST:event_jCB_comida_filtrosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_comida_aceptar;
    private javax.swing.JButton jB_comida_retorno;
    private javax.swing.JButton jB_dinero_aceptar;
    private javax.swing.JButton jB_dinero_retorno;
    private javax.swing.JButton jB_principal_Buscar;
    private javax.swing.JButton jB_principal_filtroComida;
    private javax.swing.JButton jB_principal_filtroDinero;
    private javax.swing.JButton jB_principal_filtroSugerencias;
    private javax.swing.JButton jB_principal_filtroUbicacion;
    private javax.swing.JButton jB_resultados_retorno;
    private javax.swing.JButton jB_sugerencias_enviar;
    private javax.swing.JButton jB_sugerencias_retorno;
    private javax.swing.JButton jB_ubicacion_retorno;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCB_comida_especifico;
    private javax.swing.JComboBox jCB_comida_filtros;
    private javax.swing.JLabel jL_nombreApp;
    private javax.swing.JLabel jL_principal_buscarComida;
    private javax.swing.JLabel jL_principal_buscarDistancia;
    private javax.swing.JLabel jL_principal_buscarPrecio;
    private javax.swing.JLabel jL_ubicacion_coordenadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jP_comida;
    private javax.swing.JPanel jP_comida_esconder;
    private javax.swing.JPanel jP_dinero;
    private javax.swing.JPanel jP_principal;
    private javax.swing.JPanel jP_resultados;
    private javax.swing.JPanel jP_sugerencias;
    private javax.swing.JPanel jP_ubicacion;
    private javax.swing.JSlider jS_dinero_maximo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTA_sugerencias_texto;
    private javax.swing.JTextField jTF_dinero_valor;
    private javax.swing.JTextField jTF_sugerencias_correo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private String coordenadas = "14.106610, -87.208079";
    double rango;
}
